#include <Arduino.h>
#include "s_var.h"
#include "s_pins.h"
#include "s_eeprom.h"
#include "s_wifi.h"
#include "AsyncJson.h"
#include "ArduinoJson.h"
#include "s_server.h"
#include "s_api.h"
#include <OneWire.h>
#include <DallasTemperature.h>
#include "s_18b20.h"